### ISSUE TITLE
Prévoir les changements FAQ et prise en main avant la sortie publique du Nouveau Layout

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-landing-page#136]
Avant de passer en prod la version 2.2.2 avec le nouveau layout, il faudra penser à préparer une PR de mise à jour de la documentation. 

Je m'occuperai de produire les visuels, mais il faut anticiper le travail sur les textes coté biz dev. 

Resumé des sous taches

- [ ] Récrire les textes FAQ et Prise en main (biz dev/support)
- [ ] Produire nouveau visuels, y compris pour la landing page (@areox-net)

**Comment by jdauphant** [comment]
Remplacer par la nouvelle FAQ
