### ISSUE TITLE
[WIP] Update landing content

### ISSUE THREAD

**Issue by aulamber** [tchapgouv/tchap-landing-page#169]
- [ ] "email" > "adresse mail" (everywhere)

- [ ] Add a tag in footer for stats next to "Conditions d'utilisation", cf:

<img width="694" alt="Capture d’écran 2023-04-24 à 17 04 15" src="https://user-images.githubusercontent.com/6305268/234037619-dfc441cc-54f8-446d-ac03-f3522060786b.png">

- [ ] Accessibility: non-compliant > needs to be studied

- [ ] "Tchap, la messagerie instantanée de confiance de l'Administration" > "Tchap, la messagerie instantanée de l'Administration"

- [ ] "Conçue pour les agents des trois fonctions publiques, pour communiquer facilement en toute sécurité.": "Conçue pour les agents des trois fonctions publiques, pour communiquer de manière souveraine et en toute sécurité."

**Comment by Nivann** [comment]
https://stats.tchap.incubateur.net/public/dashboard/8c6560e3-c27a-487b-b242-eb1636912f1a
