### ISSUE TITLE
Rendre juridiquement compliant la LP 

### ISSUE THREAD

**Issue by Nivann** [tchapgouv/tchap-landing-page#208]
Suite à entretien le 07/06/24 avec Perica and Co, apporter les modifications suivantes à la landing page : 

- Modifier dans le texte introduction "Conçue et gérée par l'Administration française, pour les agents des trois fonctions publiques" en "Conçue et gérée par l'Administration française, au bénéfice de la fonction publique". 

- Supprimer le tableau comparatif.

**Comment by julie-ri** [comment]
Retirer egalement la phrase "Tchap est proposé gratuitement aux administrations, collectivités et opérateurs de l’Etat" dans le à propos
Retirer dans la roadmap la phrase qui dit "cherche une solution juridique pérenne pour  offrir Tchap aux collectivités"
