### ISSUE TITLE
Contact Link mailto is not accessible on some computer

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-landing-page#52]
The mailto link will not be accessible on same cases :
- if mailto isn't setup on the user computer
- if it's setup for an email client that the user don't use

Solution :
- showing the email explicitly (we can keep the mailto if we show the email)

**Comment by estellecomment** [comment]
There are still mailto links in the code : 
https://github.com/tchapgouv/tchap-landing-page/search?q=mailto

**Comment by jdauphant** [comment]
You can have both. (the best way is a mailto on the email adress text)
