### ISSUE TITLE
Modifier FAQ pour que les liens dans l'interface pointent vers un paragraphe correspondant

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-landing-page#59]
Deux liens nécessitent un changement de la nouvelle page de FAQ pour etre cohérents : 
browser_session_info : Disable automatic logout on your browser / Désactivez la déconnexion automatique de votre navigateur 
export_info : Export your encryption keys / Exporter vos clés de chiffrement

Les deux pointent sur https://tchap.beta.gouv.fr/faq#tcq03_002 et c'est un peu trop vague. Au moins mettre en gras des morceaux de phrases pour que ca attire l'oeil.

**Comment by JDixmier** [comment]
PR faite !

**Comment by estellecomment** [comment]
fixed by https://github.com/tchapgouv/tchap-landing-page/pull/65
