### ISSUE TITLE
Ajouter une page "Presse" pour le media kit 

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-landing-page#70]
Contenu du media kit dispo ici : 
https://www.notion.so/Media-Kit-dec4b961ecbe4c54ba0313d5e052ff3b

**Comment by areox-net** [comment]
Merci @estellecomment , ça me semble assez simple. 

Je vais essayer.

**Comment by areox-net** [comment]
J'ai crée une base ici #73
Le lien à cette page se trouve dans le footer.

@JDixmier  Faut voir si les textes sont bons, notamment:

- le nom de la page
- la phrase avant le lien aux Visuels
