### ISSUE TITLE
Add new CGUs page

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-landing-page#72]

**Comment by estellecomment** [comment]
New CGU added in https://github.com/tchapgouv/tchap-landing-page/pull/91

Todo : 
 - redirect old cgu page to new one
  - remove links to old page in clients

**Comment by jdauphant** [comment]
You can create "redirect old cgu page to new one" in Tchap Infra

**Comment by jdauphant** [comment]
All tasks have been done

**Comment by jdauphant** [comment]
Maybe someone can double check

**Comment by estellecomment** [comment]
Redirection works, looks good ! All done.
